name: Deploy Application

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        cd app
        pip install -r requirements.txt
    
    - name: Setup Snyk
      uses: snyk/actions/setup@master
    
    - name: Snyk dependency scan
      run: |
        cd app
        snyk test --severity-threshold=high
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
    
    - name: Build Docker image
      run: |
        cd app
        docker build -t karalius-app .
    
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Push Docker image
      run: |
        docker tag karalius-app:latest ${{ secrets.DOCKER_USERNAME }}/karalius-app:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/karalius-app:latest
